BEGIN;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS location_code VARCHAR(50) DEFAULT 'Unknown';

ALTER TABLE order_items
ADD COLUMN IF NOT EXISTS picked BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS picker_issues (
    id SERIAL PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    substitute_product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMIT;