CREATE TABLE product_imports (
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    category_name VARCHAR(255) NOT NULL,
    price_pence INTEGER NOT NULL
);
COPY product_imports (name, description, category_name, price_pence) -- This data was generated by GPT-5.3-Codex --
FROM '/docker-entrypoint-initdb.d/product_data.csv' DELIMITER ',' CSV HEADER;
INSERT INTO products (
        name,
        description,
        category_id,
        listed,
        created_at
    )
SELECT p.name,
    p.description,
    c.id,
    TRUE,
    NOW()
FROM product_imports p
    JOIN categories c ON p.category_name = c.name;
INSERT INTO prices (product_id, price_pence, starts_at)
SELECT p.id,
    pi.price_pence,
    NOW()
FROM product_imports pi
    JOIN products p ON pi.name = p.name;
