BEGIN;

CREATE TABLE IF NOT EXISTS management_alerts (
    id SERIAL PRIMARY KEY,
    issue_id INTEGER NOT NULL REFERENCES picker_issues(id) ON DELETE CASCADE,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMP
);

COMMIT;